# Generated by Django 5.2.5 on 2025-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес студии или место съемок', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='Фотограф. Все права защищены.', max_length=200, verbose_name='Текст копирайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, help_text='Краткое описание для футера (необязательно)', verbose_name='Текст в футере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photographer_photo',
            field=models.ImageField(blank=True, help_text="Фото для страницы 'Обо мне'", null=True, upload_to='about/', verbose_name='Фото фотографа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(verbose_name='Текст о фотографе'),
        ),
    ]
