# Generated by Django 5.2.5 on 2025-09-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка (1-5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('vk', 'VKontakte')], max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID в соцсети')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка (1-5)')),
                ('photo_url', models.URLField(blank=True, verbose_name='Ссылка на фото')),
                ('post_url', models.URLField(verbose_name='Ссылка на пост')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания в соцсети')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
            ],
            options={
                'verbose_name': 'Социальный отзыв',
                'verbose_name_plural': 'Социальные отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
