# Generated by Django 5.2.5 on 2025-09-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('weekday', 'Будний день (Пн-Пт)'), ('weekend', 'Выходной (Сб-Вс)'), ('specific', 'Конкретная дата')], default='specific', max_length=10, verbose_name='Тип даты')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Конкретная дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('max_bookings', models.PositiveIntegerField(default=1, help_text='Максимальное количество броней на этот слот', verbose_name='Максимум записей')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['specific_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('shooting_type', models.CharField(choices=[('portrait', 'Портретная съемка'), ('lovestory', 'Love Story'), ('family', 'Семейная фотосессия'), ('other', 'Другое')], default='portrait', max_length=20, verbose_name='Тип съемки')),
                ('message', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('confirmation_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код подтверждения')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.timeslot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ['-created_at'],
            },
        ),
    ]
